### ISSUE TITLE
Installation problem due to astropy_helpers

### ISSUE THREAD

**Issue by fbartolic** [ebachelet/pyLIMA#20]
Hi! I'm having trouble installing pyLIMA on my Linux machine, here's the traceback:

`Installed /usr/local/lib/python2.7/dist-packages/pyLIMA-0.1.5-py2.7-linux-x86_64.egg
Processing dependencies for pyLIMA==0.1.5
Searching for astropy
Reading https://pypi.python.org/simple/astropy/
Best match: astropy 3.0rc2
Downloading https://pypi.python.org/packages/e6/a1/26cea6fc7ca04fcc0dece89c1c4a0953b24df6fb23d07bc17135461fcc2a/astropy-3.0rc2.tar.gz#md5=630f1e061033483ca6d5d77efaa7bc40
Processing astropy-3.0rc2.tar.gz
Writing /tmp/easy_install-Jot_eG/astropy-3.0rc2/setup.cfg
Running astropy-3.0rc2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Jot_eG/astropy-3.0rc2/egg-dist-tmp-p2klEQ
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    'sample': ['Claret2011.fits','Yoo_B0B1.dat'],
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-Jot_eG/astropy-3.0rc2/setup.py", line 11, in <module>
    ],
  File "/tmp/easy_install-Jot_eG/astropy-3.0rc2/astropy_helpers/astropy_helpers/__init__.py", line 46, in <module>
ImportError: No module named builtins
`
There seems to be a problem with a module within astropy_helpers. I tried running setup.py under python 3.6, 3.5 and 2.7 so it doesn't look like there's something wrong with my local python installation. For some reason  pyLIMA is pulling astropy 3.0rc2 instead of the latest stable release so that could be the source of the issue.

**Comment by ebachelet** [comment]
Hi Fran
Thanks for the spotting. It sounds like an astropy problem on recent version. May you try to replace in requirements.txt  the line : 

astropy <=> astropy==2.0

**Comment by fbartolic** [comment]
Hi Etienne, I tried doing  that, doesn't change anything.

**Comment by rachel3834** [comment]
Hi Fran, Etienne,

Fran, try pip install astropy as a standalone command and see if it will
install independently of pyLIMA.  If that works, then try pyLIMA.
Rache

**Comment by ebachelet** [comment]
Hi Fran

Any news on this?

Cheers

**Comment by fbartolic** [comment]
So I managed to get it working by running `python setup.py build_ext --build-lib=./pyLIMA/subroutines/VBBinaryLensingLibrary `  instead of `python setup.py install`. I guess you can close this.

Fran

**Comment by ebachelet** [comment]
Again, this should be close due to the separate install of VBB. Thanks again @fbartolic
