### ISSUE TITLE
Output table of parameters

### ISSUE THREAD

**Issue by rachel3834** [ebachelet/pyLIMA#33]
It would be great if pyLIMA could have a function which outputs a table/datafile summarizing the parameters of a model.  

Ideally it would be great to see two options:
* a latex-format results table
* a json-format datafile

**Comment by rachel3834** [comment]
The table output function works great, I would like to requests a couple of refinements to the formating of the table:
- \begin{tabular}{ll} -> \begin{tabular}{lll}   (There are 3 columns not 2)
- Add a header line:
Parameter & Value  & Uncertainty \\
(Otherwise its not clear what the 3rd column is for)

**Comment by rachel3834** [comment]
And it would also be great if the parameter names were in text format and latex ready, i.e. to -> $t_{0}$ etc.

**Comment by rachel3834** [comment]
Bug report when applying this function in an MCMC run:
('MCMC', ' : MCMC fit SUCCESS')
Traceback (most recent call last):
  File "Fit_event2.py", line 151, in <module>
    Model.parameters_boundaries[0]=(2458240-50.0, 2458240+50.0)     # t0
  File "build/bdist.linux-x86_64/egg/pyLIMA/microlfits.py", line 970, in produce_latex_table_results
  File "build/bdist.linux-x86_64/egg/pyLIMA/microloutputs.py", line 60, in latex_output
IndexError: index 8 is out of bounds for axis 1 with size 8
