### ISSUE TITLE
AttributeError: type object 'parameters' has no attribute 'logk_photometry_OGLE'

### ISSUE THREAD

**Issue by blackmanjw** [ebachelet/pyLIMA#72]
I get this error repeatedly when trying to run a FSBL MCMC with rescale=True, then the code stops after a few minutes.

 ```
args: []
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "/Users/odin/anaconda3/envs/py311/lib/python3.11/site-packages/emcee/ensemble.py", line 624, in __call__
    return self.f(x, *self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/odin/anaconda3/envs/py311/lib/python3.11/site-packages/pyLIMA/fits/MCMC_fit.py", line 38, in objective_function
    objective = self.standard_objective_function(fit_process_parameters)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/odin/anaconda3/envs/py311/lib/python3.11/site-packages/pyLIMA/fits/ML_fit.py", line 296, in standard_objective_function
    likelihood, pyLIMA_parameters = self.model_likelihood(
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/odin/anaconda3/envs/py311/lib/python3.11/site-packages/pyLIMA/fits/ML_fit.py", line 823, in model_likelihood
    prior = self.get_priors_probability(pyLIMA_parameters)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/odin/anaconda3/envs/py311/lib/python3.11/site-packages/pyLIMA/fits/ML_fit.py", line 348, in get_priors_probability
    probability = prior_pdf.pdf(getattr(pyLIMA_parameters, prior_key))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'parameters' has no attribute 'logk_photometry_OGLE'
```

**Comment by ebachelet** [comment]
Hi Joshua
can you print for me:

fit.priors
fit.fit_parameters 

Thanks

**Comment by ebachelet** [comment]
I believe this is fixed?
