### ISSUE TITLE
TypeError with fitting less than 5 data points

### ISSUE THREAD

**Issue by shanencross** [ebachelet/pyLIMA#8]
The following TypeError occurred when asked to LM fit an event with 3 data points: 

Traceback (most recent call last):
  File "pyLIMA_testing.py", line 75, in <module>
    main()
  File "pyLIMA_testing.py", line 72, in main
    return lima_test()
  File "pyLIMA_testing.py", line 38, in lima_test
    my_event.fit(model, "LM")
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/event.py", line 103, in fit
    fit.mlfit(model, method, flux_estimation_MCMC=flux_estimation_MCMC)
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microlfits.py", line 130, in mlfit
    self.fit_results, self.fit_covariance, self.fit_time = self.lmarquardt()
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microlfits.py", line 522, in lmarquardt
    xtol=10 *\* -10, gtol=10 *\* -5)
  File "/home/scross/anaconda2/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 380, in leastsq
    raise TypeError('Improper input: N=%s must not exceed M=%s' % (n, m))
TypeError: Improper input: N=5 must not exceed M=3

The same error occurred for a 4-point event. The same error also occurred for DE and MCMC fits as well as the LE fit of each event.

I have not tested this, but I believe you would get the same kind of error for any number of data points less than 5.

If it is impossible to fit so few points, then an error message with a more user-friendly explanation than this ( such as "Cannot fit data with fewer than 5 data points", or something) should be provided at least.

3-point data file I tested with:
7.033333E+00 1.792037E+01 5.000000E-03
1.538750E+01 1.594927E+01 5.000000E-03
2.432500E+01 1.802630E+01 5.000000E-03

4-point data file I tested with:
0.000000E+00 2.493251E+01 2.235931E-01
8.354167E+00 2.434087E+01 1.417376E-01
1.729167E+01 2.362907E+01 8.190474E-02
2.622917E+01 2.502962E+01 2.409634E-01

**Comment by ebachelet** [comment]
Hi Shanen

I think the problem come from the call of the scipy.leastsq function. Could
you have a try with MCMC   with guess settings. Before calling fit, just
add :

Model.parameters_guess = [to,uo,tE]

It shouldn't fail with this.

Cheers
2016-09-12 14:13 GMT-07:00 shanencross <notifications@github.com>:

**Comment by shanencross** [comment]
Yes, this works with a guesses for at least model.parameters_guess [15, 0.1, 10] (those are the theoretical to, uo, and tE for these data points) and some similar guesses.

However, there should at least still be a more human-readable error for MCMC fits without guesses and for LM and DE fits.

**Comment by ebachelet** [comment]
Agree, working on this now.

2016-09-12 15:35 GMT-07:00 shanencross <notifications@github.com>:

**Comment by shanencross** [comment]
Tested newest version.

LM fit outputs the good human-readable error message, but then encounters a new, different error:

You do not have enough data points to use this method (LM), please switch to other methods.                                                                             
Traceback (most recent call last):                                                                                                                                      
  File "pyLIMA_testing.py", line 76, in <module>                                                                                                                        
    main()                                                                                                                                                              
  File "pyLIMA_testing.py", line 73, in main                                                                                                                            
    return lima_test()                                                                                                                                                  
  File "pyLIMA_testing.py", line 41, in lima_test                                                                                                                       
    fit.produce_outputs()
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microlfits.py", line 780, in produce_outputs
    outputs = microloutputs.LM_outputs(self)
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microloutputs.py", line 51, in LM_outputs
    results = LM_parameters_result(fit)
  File "/home/scross/Documents/LCOGT/Workspace/galactic_microlensing_simulation/pyLIMA/microloutputs.py", line 385, in LM_parameters_result
    setattr(fit_parameters, parameter, fit.fit_results[fit.model.model_dictionnary[parameter]])
IndexError: list index out of range

DE and MCMC fits outputs the good error message, but then they both put the user in the (pdb). Don't know if this is intentional, but it is probably confusing to users. 

Also the DE and MCMC error messages say the user does not "have enough data points to use this method (LM)". They should say DE and MCMC, respectively, instead of LM.

Finally, it might be a good idea to tell the user the minimum number of points needed to for a fit in the error message (such as "You need at least 5 data points to use the LM method").

**Comment by ebachelet** [comment]
'Traceback (most recent call last):

File "pyLIMA_testing.py", line 76, in

main()

File "pyLIMA_testing.py", line 73, in main

return lima_test()

File "pyLIMA_testing.py", line 41, in lima_test

fit.produce_outputs()'

That make sens, you try to produce outputs on an event where there is no fit, leading to anerror because there is no fit.fit_results parameters. Maybe should I add a condition on this, like if no fit return nothing.
"
DE and MCMC fits output the good error message, but then they both put the user in the (pdb) debug text entry mode. Don't know if this is intentional, but it is probably confusing to users.

Also the DE and MCMC error messages say the user does not "have enough data points to use this method (LM)". They should say DE and MCMC, respectively, instead of LM.
"

I think you misunderstood here. We use the LM method inside DE also (note that DE is used by MCMC) to determinate the covariance matrix (and also to converge to the best solution around this minima).
"
Finally, it might be a good idea to tell the user the minimum number of points needed to for a fit in the error message (such as "You need at least 5 data points to use the LM method").
"
Done
