### ISSUE TITLE
ModuleNotFoundError: No module named 'pyLIMA.models.DFSPL_model' (DoubleSource branch)

### ISSUE THREAD

**Issue by ytsapras** [ebachelet/pyLIMA#82]
This error happens during importing the modules at the start of the code. DFSPL_model does not exist.

```
from pyLIMA.outputs import pyLIMA_plots
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Tux/ytsapras/Installed_Programs/pyLIMA/pyLIMA/outputs/pyLIMA_plots.py", line 7, in <module>
    import pyLIMA.fits.objective_functions
  File "/home/Tux/ytsapras/Installed_Programs/pyLIMA/pyLIMA/fits/__init__.py", line 1, in <module>
    from .BOOTSTRAP_fit import BOOTSTRAPfit
  File "/home/Tux/ytsapras/Installed_Programs/pyLIMA/pyLIMA/fits/BOOTSTRAP_fit.py", line 6, in <module>
    from pyLIMA.models import generate_model
  File "/home/Tux/ytsapras/Installed_Programs/pyLIMA/pyLIMA/models/__init__.py", line 1, in <module>
    from .DFSPL_model import DFSPLmodel
ModuleNotFoundError: No module named 'pyLIMA.models.DFSPL_model'
```

It tries to import it and complains at several places, for example when you do:
`from pyLIMA.outputs import pyLIMA_plots
`or `from pyLIMA.models import USBL_model`

You will probably need to remove it from __init__.py
```
__init__.py:from .DFSPL_model import DFSPLmodel
__init__.py:__all__ = ["DFSPLmodel", "DSPLmodel", "FSBLmodel", "FSPLmodel", "FSPLargemodel
```

**Comment by ytsapras** [comment]
This also applies to DSPL_model
`ModuleNotFoundError: No module named 'pyLIMA.models.DSPL_model'`

**Comment by ytsapras** [comment]
Fixed in the DoubleSource branch.
