### ISSUE TITLE
UnboundLocalError: local variable 'source1_trajectory_x' referenced before assignment when doing USBL with parallax fit.

### ISSUE THREAD

**Issue by ytsapras** [ebachelet/pyLIMA#83]
I think I may have encountered a bug.
I defined:
```
    usblp = USBL_model.USBLmodel(current_event, parallax=['Full', 2459409.77],
                                   fancy_parameters=fancy)
    # Specify fitting algorithm [LM_fit, TRF_fit, DE_fit, MCMC_fit, GRIDS_fit]:
    from pyLIMA.fits import DE_fit, MCMC_fit, TRF_fit
    fit_4 = DE_fit.DEfit(usblp, telescopes_fluxes_method='polyfit',
                         DE_population_size=18, max_iteration=10000,
                         display_progress=True, strategy='best1bin')
```
then when doing a` fit_4.fit()`
it crashes with:
```
line 935, in sources_trajectory
    return (source1_trajectory_x, source1_trajectory_y,
UnboundLocalError: local variable 'source1_trajectory_x' referenced before assignment
```

**Comment by ytsapras** [comment]
This is probably a related bug:
```
>>> pyLIMA_plots.plot_geometry(usblpom, fit_5.fit_results['best_model'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pyLIMA/pyLIMA/outputs/pyLIMA_plots.py", line 423, in plot_geometry
    (trajectory_x[origin_t0par_index], trajectory_y[origin_t0par_index]))
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ytsapras** [comment]
```
  File "/pyLIMA/pyLIMA/outputs/pyLIMA_plots.py", line 423, in plot_geometry
    (trajectory_x[origin_t0par_index], trajectory_y[origin_t0par_index]))
```

This particular bug occurs because trajectory_x is None. This happens earlier on in the code, when there is only a single source,  when the code does
```
for ind, trajectory in enumerate([[source1_trajectory_x,
                                             source1_trajectory_y],
                               [source2_trajectory_x, source2_trajectory_y]])

    trajectory_x, trajectory_y = trajectory
```
This can produce a trajectory_x which is None.

**Comment by ytsapras** [comment]
This has now been fixed in the DoubleSource branch.

**Comment by ebachelet** [comment]
I believe this is now fixed
