### ISSUE TITLE
Error with plot_geometry for a specific event while producing outputs

### ISSUE THREAD

**Issue by KKruszynska** [ebachelet/pyLIMA#97]
I run into this error when I try to produce a fit_outputs for event AT2024kwu:
```
/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/pyLIMA/fits/TRF_fit.py:32: RuntimeWarning: divide by zero encountered in log10
  scaling = 10**np.floor(np.log10(np.abs(self.guess)))+1
Trust Region Reflective fit SUCCESS
best model:
OrderedDict([('t0', 2460613.3971494907),
             ('u0', 0.25788872584168293),
             ('tE', 98.44073172768847),
             ('piEN', 0.0626788235611856),
             ('piEE', -0.39534582214796793),
             ('fsource_LCO_r', 13001.436716652763),
             ('ftotal_LCO_r', 6690.951996482346),
             ('fsource_ZTF_r', 11962.463314521823),
             ('ftotal_ZTF_r', 11093.553926041057),
             ('fsource_Gaia_G', 10178.718568620081),
             ('ftotal_Gaia_G', 9624.91838288255),
             ('fsource_ZTF_g', 6443.280574459705),
             ('ftotal_ZTF_g', 5897.175400514652),
             ('fsource_LCO_g', 6505.047173809507),
             ('ftotal_LCO_g', 4637.533254665568),
             ('fsource_LCO_i', 14800.066607494546),
             ('ftotal_LCO_i', 11445.493021362692),
             ('soft_l1', np.float64(1650.3388887102024))])
============== test test test ==============
2460626.0 2460613.397
/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/erfa/core.py:133: ErfaWarning: ERFA function "utctai" yielded 624 of "dubious year (Note 3)"
  warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)
/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/erfa/core.py:133: ErfaWarning: ERFA function "taiutc" yielded 624 of "dubious year (Note 4)"
  warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)
/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/erfa/core.py:133: ErfaWarning: ERFA function "utcut1" yielded 624 of "dubious year (Note 3)"
  warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)
Parallax(Full) estimated for the telescope LCO_r: SUCCESS
Successfully ephemeris from JPL!
Parallax(Full) estimated for the telescope Gaia_G: SUCCESS
Traceback (most recent call last):
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/Microlensing_Fitting_Pipeline/MFPipeline/analyst/event_analyst.py", line 383, in <module>
    event_analyst.run_single_analyst()
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/Microlensing_Fitting_Pipeline/MFPipeline/analyst/event_analyst.py", line 184, in run_single_analyst
    self.run_fit_analyst()
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/Microlensing_Fitting_Pipeline/MFPipeline/analyst/event_analyst.py", line 228, in run_fit_analyst
    fit_analyst.perform_fit()
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/MFPipeline/analyst/fit_analyst.py", line 391, in perform_fit
    self.perform_ongoing_fit(t_0)
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/MFPipeline/analyst/fit_analyst.py", line 221, in perform_ongoing_fit
    results = self.fit_PSPL(self.analyst_path+"_PSPL_blend_piE",
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/MFPipeline/analyst/fit_analyst.py", line 155, in fit_PSPL
    results = fit_pspl.fit_PSPL(fit_name, self.light_curves, starting_params, parallax, blend,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/MFPipeline/fitting_support/pyLIMA/fit_pyLIMA.py", line 177, in fit_PSPL
    plots_pyLIMA.plot_pyLIMA(event, fit_event, self.log)
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/MFPipeline/fitting_support/pyLIMA/plots_pyLIMA.py", line 63, in plot_pyLIMA
    fit.fit_outputs(bokeh_plot=True)
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/pyLIMA/fits/ML_fit.py", line 1273, in fit_outputs
    matplotlib_geometry, bokeh_geometry = pyLIMA_plots.plot_geometry(self.model,
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katarzyna/Documents/Microlensing_Fitting_Pipeline/.venv/lib/python3.11/site-packages/pyLIMA/outputs/pyLIMA_plots.py", line 361, in plot_geometry
    (source1_trajectory_x[origin_t0par_index],
     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: index 1865 is out of bounds for axis 0 with size 524
```
This error doesn't occur when I perform the same fit inside a jupyter notebook.

**Comment by ebachelet** [comment]
I added Yiannis since it seems he has a similar issue

**Comment by ytsapras** [comment]
I did some tracking of where it fails and it is the old culprit: trajectory_x and trajectory_y are None. When I run the code for Gaia21ccu and the parameter ranges considered, this happens when origin_t0par_index is 4286.
I printed out all the values of the parameters that are passed in the call to microlensing_model.sources_trajectory and they look reasonable:

```
tau: [-8.29353488 -8.26334506 -8.23042404 ...  8.20145419  8.23620792
  8.26811703], beta: [ 0.93341008  0.91059211  0.88551579 ... -2.59570968 -2.58972521
 -2.58561257], alpha: [4.0707429  4.07344239 4.07614923 ... 4.06193782 4.06461479 4.06729838]
dseparation: [2.56586025 2.56034015 2.55467214 ... 2.58291426 2.5778866  2.57270758], dalpha: [1.10003642 1.09733692 1.09463009 ... 1.1088415  1.10616452 1.10348093]
parallax_delta_tau: [-3.29352622 -3.29131637 -3.28637533 ...  3.26857207  3.27534583
  3.27927497], parallax_delta_beta: [ 1.72153055  1.69871258  1.67363626 ... -1.80758921 -1.80160474
 -1.7974921 ]
source1_trajectory_x: [-5.71157025 -5.65880175 -5.60256537 ...  7.03204722  7.03495633
  7.03739917], source1_trajectory_y: [-6.08538745 -6.090157   -6.09387229 ...  4.9549845   5.00511609
  5.05194661]
tau: [-11.87425228 -11.87424751 -11.87347351 ...   3.62196352   3.65241689
   3.65276258], beta: [ 1.72568055  1.72568112  1.72577296 ... -1.70697671 -1.72666008
 -1.72687742], alpha: [3.8530954  3.85309586 3.85316989 ... 3.8012472  3.80354807 3.80357336]
dseparation: [2.36579789 2.36579993 2.36613111 ... 2.09062203 2.10455882 2.10471119], dalpha: [1.31768391 1.31768346 1.31760943 ... 1.36953212 1.36723125 1.36720596]
parallax_delta_tau: [-4.59177295 -4.59177246 -4.59169413 ...  1.33528744  1.34697462
  1.34711323], parallax_delta_beta: [ 2.51380102  2.51380159  2.51389343 ... -0.91885624 -0.93853961
 -0.93875695]
source1_trajectory_x: [-10.12016096 -10.12015478 -10.11915132 ...   3.9082003    3.94230623
   3.94269017], source1_trajectory_y: [-6.44656363 -6.4465647  -6.44673887 ...  0.87083847  0.88302081
  0.88316158]

```

Then, just before the problem occurs, I print out the values:
```
 print(telescope.lightcurve_magnitude['time'].value,
              microlensing_model.parallax_model[1],
              origin_t0par_index)

        print(trajectory_x, trajectory_y)
```
which returns:
```
[2457693.93 2457703.93 2457713.93 ... 2461243.93 2461253.93 2461263.93] 2459449.68 4286
None None
```

So even though the time value is within the range, the trajectories are not set.

For reference, here are the model parameter starting points and ranges, in case you spot some obvious problem that I have missed:
```
fit_10.model_parameters_guess = np.array([ 2.45947605e+06, -7.83271517e-01,  2.55384946e+00, -2.48389165e+00, 1.90481237e-01, -8.01356129e-01,  5.16003209e+00,  8.49193961e-02, -8.95796006e-02, -4.24575669e-01, -7.12624112e-01,  2.35562038e+00, -3.86682080e+00,  9.70852213e-01])
fit_10.fit_parameters
OrderedDict([('t0', [0, [2459450.0, 2459490.0]]), ('u0', [1, (-1.0, 1.0)]), ('log_tE', [2, (1.7, 2.6)]), ('log_rho', [3, [-4.4, -1.9]]), ('log_separation', [4, (0.1, 0.9)]), ('log_mass_ratio', [5, [-1.4, -0.1]]), ('alpha', [6, (0.0, 6.283185307179586)]), ('piEN', [7, (-0.5, 0.5)]), ('piEE', [8, (-0.5, 0.5)]), ('v_para', [9, (-10.0, 10.0)]), ('v_perp', [10, (-10.0, 10.0)]), ('v_radial', [11, (-10.0, 10.0)]), ('r_s', [12, (-10, 10)]), ('a_s', [13, (0.500001, 10)])])

```

So the key issue appears to be that _trajectory_x_ and _trajectory_y_ are _None_ at some point in the execution. Maybe _telescope.lightcurve_flux['time'].value_ has values that don't align with the computed trajectories' time ranges? This could perhaps be "fixed" by doing a boundary check before accessing the trajectory arrays and checking that _origin_t0par_index_ is within the bounds of _source1_trajectory_x_ and _source1_trajectory_y_ before trying to index them. I haven't yet had a chance to explore this further.

**Comment by ebachelet** [comment]
I believe this is now fixed.
